"""RulesFile — value object for .claude/rules/wos-context.md."""
from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict

from wos.models.core import IssueSeverity, ValidationIssue


class RulesFile(BaseModel):
    """The behavioral guide for agents (.claude/rules/wos-context.md)."""

    model_config = ConfigDict(frozen=True)

    content: str

    # ── String representations ────────────────────────────────────

    def __str__(self) -> str:
        lines = self.content.count("\n")
        return f"RulesFile ({lines} lines)"

    def __repr__(self) -> str:
        return f"RulesFile(content_length={len(self.content)})"

    # ── Markdown protocol ─────────────────────────────────────────

    def to_markdown(self) -> str:
        return self.content

    # ── JSON protocol ─────────────────────────────────────────────

    def to_json(self) -> dict:
        return {"content": self.content}

    @classmethod
    def from_json(cls, data: dict) -> RulesFile:
        return cls(**data)

    # ── Validation protocol ───────────────────────────────────────

    def validate_self(self, deep: bool = False) -> List[ValidationIssue]:
        issues: List[ValidationIssue] = []
        if not self.content.strip():
            issues.append(
                ValidationIssue(
                    file=".claude/rules/wos-context.md",
                    issue="Rules file is empty",
                    severity=IssueSeverity.WARN,
                    validator="RulesFile.validate_self",
                    suggestion="Generate rules file via discovery",
                )
            )
        return issues

    @property
    def is_valid(self) -> bool:
        return len(self.validate_self()) == 0

    # ── Factory ───────────────────────────────────────────────────

    @classmethod
    def render(cls) -> RulesFile:
        """Generate the standard rules file content.

        Produces the same content as discovery.render_rules_file().
        """
        content = """\
# WOS Context Rules

## Document Types

| Type | Directory | Purpose |
|------|-----------|---------|
| topic | `context/{area}/{slug}.md` | Actionable guidance with citations |
| overview | `context/{area}/_overview.md` | Area orientation and topic index |
| research | `artifacts/research/{date}-{slug}.md` | Investigation snapshot |
| plan | `artifacts/plans/{date}-{slug}.md` | Actionable work plan |

## Frontmatter Requirements

All documents require YAML frontmatter with `document_type`, `description`,
and `last_updated`. Additional requirements by type:

- **topic**: `sources` (list of url+title), `last_validated` (date)
- **overview**: `last_validated` (date)
- **research**: `sources` (list of url+title)
- **plan**: (optional `status` string)

Optional on all types: `tags` (lowercase-hyphenated), `related` (file paths or URLs).

## Agent Guidelines

- Use `/wos:discover` to find and access context before reading full files
- Context types (topic, overview) appear in the AGENTS.md manifest
- Artifact types (research, plan) are internal \u2014 reachable via `related` links
- Use `/wos:create-document` to create new documents
- Use `/wos:update-document` to update existing documents
- Use `/wos:audit` to check document validity
- Use `/wos:fix` to fix issues found by audit
- `related` uses root-relative file paths (e.g., `context/python/error-handling.md`)
- Never edit content between wos markers manually \u2014 auto-generated by discovery
"""
        return cls(content=content)
